/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVocabularyRouteImport } from './routes/app/vocabulary'
import { Route as AppReadingListRouteImport } from './routes/app/reading-list'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAppRouteImport } from './routes/app/app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/app/vocabulary',
  path: '/app/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReadingListRoute = AppReadingListRouteImport.update({
  id: '/app/reading-list',
  path: '/app/reading-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app/app',
  path: '/app/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/app': typeof AppAppRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reading-list': typeof AppReadingListRoute
  '/app/vocabulary': typeof AppVocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/app': typeof AppAppRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reading-list': typeof AppReadingListRoute
  '/app/vocabulary': typeof AppVocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/app': typeof AppAppRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reading-list': typeof AppReadingListRoute
  '/app/vocabulary': typeof AppVocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/app'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/reading-list'
    | '/app/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/app'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/reading-list'
    | '/app/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/app/app'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/reading-list'
    | '/app/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppRoute: typeof AppAppRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReadingListRoute: typeof AppReadingListRoute
  AppVocabularyRoute: typeof AppVocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vocabulary': {
      id: '/app/vocabulary'
      path: '/app/vocabulary'
      fullPath: '/app/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reading-list': {
      id: '/app/reading-list'
      path: '/app/reading-list'
      fullPath: '/app/reading-list'
      preLoaderRoute: typeof AppReadingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/app': {
      id: '/app/app'
      path: '/app/app'
      fullPath: '/app/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppRoute: AppAppRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppReadingListRoute: AppReadingListRoute,
  AppVocabularyRoute: AppVocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
